# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1672, 876)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 50, 281, 751))
        self.scrollArea.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.738636, y1:1, x2:0, y2:1, stop:0 rgba(0, 0, 34, 255), stop:0.357955 rgba(0, 0, 32, 255), stop:0.488636 rgba(0, 3, 43, 255), stop:0.761364 rgba(0, 0, 52, 255), stop:1 rgba(0, 0, 70, 255));\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 279, 749))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(-10, 0, 291, 61))
        self.label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.284, y1:0.948636, x2:1, y2:0.916, stop:0.4375 rgba(0, 0, 64, 255), stop:0.568182 rgba(0, 0, 93, 255), stop:0.670455 rgba(0, 0, 102, 255), stop:0.789773 rgba(0, 18, 117, 255), stop:0.954545 rgba(0, 57, 142, 255), stop:1 rgba(0, 81, 127, 255));\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 10pt \"Segoe UI Variable Small\";\n"
"")
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(290, 420, 211, 61))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.284, y1:0.948636, x2:1, y2:0.916, stop:0.4375 rgba(0, 0, 64, 255), stop:0.568182 rgba(0, 0, 93, 255), stop:0.670455 rgba(0, 0, 102, 255), stop:0.789773 rgba(0, 18, 117, 255), stop:0.954545 rgba(0, 57, 142, 255), stop:1 rgba(0, 81, 127, 255));\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"gridline-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 10pt \"Segoe UI Variable Small\";\n"
"")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(290, 240, 211, 61))
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_2.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.284, y1:0.948636, x2:1, y2:0.916, stop:0.4375 rgba(0, 0, 64, 255), stop:0.568182 rgba(0, 0, 93, 255), stop:0.670455 rgba(0, 0, 102, 255), stop:0.789773 rgba(0, 18, 117, 255), stop:0.954545 rgba(0, 57, 142, 255), stop:1 rgba(0, 81, 127, 255));\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 75 10pt \"Segoe UI Variable Small\";\n"
"")
        self.toolButton_2.setObjectName("toolButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -1, 1671, 51))
        self.label_2.setStyleSheet("font: 75 12pt \"HP Simplified\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"background-color: qlineargradient(spread:reflect, x1:0.284, y1:0.948636, x2:1, y2:0.916, stop:0.4375 rgba(0, 0, 64, 255), stop:0.568182 rgba(0, 0, 93, 255), stop:0.670455 rgba(0, 0, 102, 255), stop:0.789773 rgba(0, 18, 117, 255), stop:0.954545 rgba(0, 57, 142, 255), stop:1 rgba(0, 81, 127, 255));\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1672, 21))
        self.menubar.setObjectName("menubar")
        self.menuIM_VEIS = QtWidgets.QMenu(self.menubar)
        self.menuIM_VEIS.setObjectName("menuIM_VEIS")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_procurar = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main(images)/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_procurar.setIcon(icon)
        self.action_procurar.setObjectName("action_procurar")
        self.action_cadastrar = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main(images)/create.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_cadastrar.setIcon(icon1)
        self.action_cadastrar.setObjectName("action_cadastrar")
        self.action_apagar = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main(images)/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_apagar.setIcon(icon2)
        self.action_apagar.setObjectName("action_apagar")
        self.action_atualizar = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/main(images)/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_atualizar.setIcon(icon3)
        self.action_atualizar.setObjectName("action_atualizar")
        self.menuIM_VEIS.addAction(self.action_procurar)
        self.menuIM_VEIS.addAction(self.action_cadastrar)
        self.menuIM_VEIS.addAction(self.action_apagar)
        self.menuIM_VEIS.addAction(self.action_atualizar)
        self.menubar.addAction(self.menuIM_VEIS.menuAction())
        self.toolBar.addAction(self.action_procurar)
        self.toolBar.addAction(self.action_cadastrar)
        self.toolBar.addAction(self.action_apagar)
        self.toolBar.addAction(self.action_atualizar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "                                IMÓVEIS"))
        self.toolButton.setText(_translate("MainWindow", "Adicionar Gasto "))
        self.toolButton_2.setText(_translate("MainWindow", "Ver Gastos"))
        self.label_2.setText(_translate("MainWindow", "                                                                                                                                                                                                           CONTROLE DE GASTOS"))
        self.menuIM_VEIS.setTitle(_translate("MainWindow", "Opções"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_procurar.setText(_translate("MainWindow", "procurar"))
        self.action_procurar.setToolTip(_translate("MainWindow", "Procurar Imóvel"))
        self.action_cadastrar.setText(_translate("MainWindow", "cadastrar"))
        self.action_cadastrar.setToolTip(_translate("MainWindow", "Cadastrar Imóvel"))
        self.action_apagar.setText(_translate("MainWindow", "apagar"))
        self.action_apagar.setToolTip(_translate("MainWindow", "Apagar Imóvel"))
        self.action_atualizar.setText(_translate("MainWindow", "atualizar"))
        self.action_atualizar.setToolTip(_translate("MainWindow", "Atualizar Tela"))
import resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
